import i18n from '../../utils/translation'
function strings() {
  return {
    header_theory: i18n.t("header.theory"),
    header_recommend: i18n.t("header.recommend"),
    header_analysis: i18n.t("header.analysis"),
    fail_request: i18n.t("error_request.fail_request"),
    error_network: i18n.t("error_request.error_network"),
    height: i18n.t("table_data.height"),
    bust: i18n.t("table_data.bust"),
    name: i18n.t("table_data.name"),
    _name: i18n.t("table_data._name"),
    birthday: i18n.t("table_data.birthday"),
    cluster: i18n.t("table_data.cluster"),
    cup_size: i18n.t("table_data.cup_size"),
    imgurl: i18n.t("table_data.imgurl"),
    search: i18n.t("table_data.search"),
    waist: i18n.t("table_data.waist"),
    birthplace: i18n.t("table_data.birthplace"),
    hobby: i18n.t("table_data.hobby"),
    hip: i18n.t("table_data.hip"),
    age: i18n.t("table_data.age"),
    top_tallest: i18n.t("top.top_tallest"),
    top_lowest_dimensions: i18n.t("top.top_lowest_dimensions"),
    top_youngest: i18n.t("top.top_youngest"),
    top_oldest: i18n.t("top.top_oldest"),
    top_smallest_hips: i18n.t("top.top_smallest_hips"),
    top_biggest_hips: i18n.t("top.top_biggest_hips"),
    top_smallest_bust: i18n.t("top.top_smallest_bust"),
    top_biggest_bust: i18n.t("top.top_biggest_bust"),
    err_input: i18n.t("messenger.err_input"),
    err_data: i18n.t("messenger.err_data"),
    input_data: i18n.t('input_data', {
      returnObjects: true,
    }),
    analysis_tab_big_header: i18n.t('analysis_tab.big_header'),
    analysis_tab_child_header: i18n.t('analysis_tab.child_header'),
    analysis_tab_txt_bnt_header: i18n.t('analysis_tab.txt_bnt_header'),
    step: i18n.t('step', { returnObjects: true }),
    analysis_tab_img_description: i18n.t('analysis_tab.img_description', {
      returnObjects: true,
    }),
    analysis_tab_content_header1: i18n.t('analysis_tab.content.header1'),
    analysis_tab_content_content1: i18n.t('analysis_tab.content.content1', {
      returnObjects: true,
    }),
    analysis_tab_content_header2: i18n.t('analysis_tab.content.header2'),
    analysis_tab_content_content2: i18n.t('analysis_tab.content.content2', {
      returnObjects: true,
    }),
    analysis_tab_content_step_content2: i18n.t(
      'analysis_tab.content.step_content2',
      {
        returnObjects: true,
      }
    ),

    analysis_tab_content_header3: i18n.t('analysis_tab.content.header3'),
    analysis_tab_content_content3: i18n.t('analysis_tab.content.content3', {
      returnObjects: true,
    }),
    topic: i18n.t("topic"),
    title1: i18n.t("title.title1.title"),
    contend11: i18n.t("title.title1.contend1"),
    contend12: i18n.t("title.title1.contend2"),
    contend13: i18n.t("title.title1.contend3"),
    contend14: i18n.t("title.title1.contend4", { returnObjects: true }),
    contend15: i18n.t("title.title1.contend5"),
    title2: i18n.t("title.title2.title"),
    contend21: i18n.t("title.title2.contend1"),
    contend22: i18n.t("title.title2.contend2"),
    contend23: i18n.t("title.title2.contend3"),
    contend24: i18n.t("title.title2.contend4", { returnObjects: true }),
    contend25: i18n.t("title.title2.contend5"),
    contend26: i18n.t("title.title2.contend6"),
    contend27: i18n.t("title.title2.contend7"),
    contend28: i18n.t("title.title2.contend8"),
    contend29: i18n.t("title.title2.contend9"),
    contend210: i18n.t("title.title2.contend10"),
    contend211: i18n.t("title.title2.contend11"),
    contend212: i18n.t("title.title2.contend12"),
    contend213: i18n.t("title.title2.contend13"),
    contend214: i18n.t("title.title2.contend14"),
    contend215: i18n.t("title.title2.contend15"),
    contend216: i18n.t("title.title2.contend16"),
    contend217: i18n.t("title.title2.contend17"),
    contend218: i18n.t("title.title2.contend18"),
    contend219: i18n.t("title.title2.contend19"),
    contend220: i18n.t("title.title2.contend20"),
  };
}
export default strings